package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"github.com/4x2Hach1/learning/gql-go/api/execs"
)

// Mutation returns execs.MutationResolver implementation.
func (r *Resolver) Mutation() execs.MutationResolver { return &mutationResolver{r} }

// Query returns execs.QueryResolver implementation.
func (r *Resolver) Query() execs.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
