openapi: 3.0.3
info:
    title: Api Server Service
    description: Api server server for front.
    version: 0.0.1
servers:
    - url: http://localhost:4000
paths:
    /hello/{name}:
        get:
            tags:
                - server
            summary: hello server
            operationId: server#hello
            parameters:
                - name: name
                  in: path
                  description: Name
                  required: true
                  schema:
                    type: string
                    description: Name
                    example: Et veritatis non nostrum.
                  example: Explicabo quas est minus.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Eveniet vel nesciunt omnis est ducimus est.
                            example: Aut mollitia illum quia.
components: {}
tags:
    - name: server
      description: Server Service for front.
