swagger: "2.0"
info:
    title: Api Server Service
    description: Api server server for front.
    version: 0.0.1
host: localhost:4000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /hello/{name}:
        get:
            tags:
                - server
            summary: hello server
            operationId: server#hello
            parameters:
                - name: name
                  in: path
                  description: Name
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
    /users:
        get:
            tags:
                - server
            summary: users server
            operationId: server#users
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/UserResponse'
            schemes:
                - http
definitions:
    UserResponse:
        title: 'Mediatype identifier: user; view=default'
        type: object
        properties:
            email:
                type: boolean
                description: Email
                example: false
            id:
                type: integer
                description: ID
                example: 5662336933204789771
                format: int64
            name:
                type: string
                description: Name
                example: In aut mollitia illum.
        description: UserResponse result type (default view)
        example:
            email: false
            id: 5630377860693557564
            name: Quis exercitationem ut ipsum.
