openapi: 3.0.3
info:
    title: Api Server Service
    description: Api server server for front.
    version: 0.0.1
servers:
    - url: http://localhost:4000
paths:
    /hello/{name}:
        get:
            tags:
                - server
            summary: hello server
            operationId: server#hello
            parameters:
                - name: name
                  in: path
                  description: Name
                  required: true
                  schema:
                    type: string
                    description: Name
                    example: Quia sit ut aut tenetur consequatur.
                  example: Quasi at omnis aut consequatur id.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Minus cum.
                            example: Cumque nostrum aut.
    /users:
        get:
            tags:
                - server
            summary: users server
            operationId: server#users
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/User'
                                example:
                                    - email: false
                                      id: 8125601974708616722
                                      name: Praesentium sunt cum aut blanditiis accusantium.
                                    - email: false
                                      id: 8125601974708616722
                                      name: Praesentium sunt cum aut blanditiis accusantium.
                                    - email: false
                                      id: 8125601974708616722
                                      name: Praesentium sunt cum aut blanditiis accusantium.
                                    - email: false
                                      id: 8125601974708616722
                                      name: Praesentium sunt cum aut blanditiis accusantium.
                            example:
                                - email: false
                                  id: 8125601974708616722
                                  name: Praesentium sunt cum aut blanditiis accusantium.
                                - email: false
                                  id: 8125601974708616722
                                  name: Praesentium sunt cum aut blanditiis accusantium.
components:
    schemas:
        User:
            type: object
            properties:
                email:
                    type: boolean
                    description: Email
                    example: false
                id:
                    type: integer
                    description: ID
                    example: 6104545963114438964
                    format: int64
                name:
                    type: string
                    description: Name
                    example: Eum officiis qui et et dolor fuga.
            example:
                email: true
                id: 3819334598922553237
                name: Deserunt voluptates.
tags:
    - name: server
      description: Server Service for front.
