apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: api
        image: k8s-api-prod:1.0.1
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
