services:
  k8s-api:
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: k8s-api
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 8585:8080
