version: "3.8"

services:
  gql-go-api:
    tty: true
    build: ./api
    container_name: gql-go-api
    working_dir: /app
    volumes:
      - ./api:/app
  gql-go-db:
    image: mysql:8.0.33
    container_name: gql-go-db
    environment:
      MYSQL_DATABASE: gql
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 5005:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
